// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revision.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const altaRevisionEntrega = `-- name: AltaRevisionEntrega :one


INSERT INTO revision_entregas (aparato_id, persona, persona_nombre, branch_id, token_jti, desde_ip, agente, version_app)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (aparato_id, token_jti) DO UPDATE SET updated_at = now()
RETURNING id, aparato_id, persona, persona_nombre, branch_id, token_jti, desde_ip, agente, version_app, entregada_at, created_at, updated_at
`

type AltaRevisionEntregaParams struct {
	AparatoID     uuid.UUID `json:"aparato_id"`
	Persona       string    `json:"persona"`
	PersonaNombre *string   `json:"persona_nombre"`
	BranchID      uuid.UUID `json:"branch_id"`
	TokenJti      string    `json:"token_jti"`
	DesdeIp       *string   `json:"desde_ip"`
	Agente        *string   `json:"agente"`
	VersionApp    *string   `json:"version_app"`
}

// Las consultas de LA BANDEJA DE REVISIÓN (`docs/bandeja-de-revision.md`, B.2), para sqlc.
//
// Sólo contabilidad de la sincronización: nada de aquí toca pedidos, rutas ni tablero.
//
// Mismas convenciones que `sync.sql`: el alcance por sucursal es SEGURIDAD y va en el SQL, nunca en
// Go (`sqlc.narg('sucursal')::uuid IS NULL OR e.branch_id = …`: NULL es «todas», el Super Admin);
// y lo que se decide va en la propia sentencia (`WHERE estado IN (…)`), no en un «leer y luego
// escribir».
//
// «Vivo» = `en_revision`, `aplicando`, `rechazado`: lo que sigue esperando a una persona. Es lo que
// cuentan los cupos y el número rojo de `/sync/estado`.
//
// QUÉ ES DE S1 Y QUÉ DE S2. La entrega (lo primero) la usa S1. Lo de «El revisor» y «El libro» lo
// usará S2 (listar, aplicar, descartar); está aquí para que S2 empiece con migración, consultas y
// dobles ya entregados, y está probado contra Postgres de verdad (`revision_motor_real_test.go`).
// ===========================================================================
// 1 · La entrega
// ===========================================================================
// Una fila por token de entrega: la app manda los apuntes de uno en uno, y todos los que llegan con el
// mismo `jti` caen en la MISMA entrega. El `DO UPDATE` no cambia nada: devuelve la fila que manda.
func (q *Queries) AltaRevisionEntrega(ctx context.Context, arg AltaRevisionEntregaParams) (RevisionEntrega, error) {
	row := q.db.QueryRow(ctx, altaRevisionEntrega,
		arg.AparatoID,
		arg.Persona,
		arg.PersonaNombre,
		arg.BranchID,
		arg.TokenJti,
		arg.DesdeIp,
		arg.Agente,
		arg.VersionApp,
	)
	var i RevisionEntrega
	err := row.Scan(
		&i.ID,
		&i.AparatoID,
		&i.Persona,
		&i.PersonaNombre,
		&i.BranchID,
		&i.TokenJti,
		&i.DesdeIp,
		&i.Agente,
		&i.VersionApp,
		&i.EntregadaAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const anotarRevisionDecision = `-- name: AnotarRevisionDecision :one

INSERT INTO revision_decisiones (aparato_id, clave, accion, por, por_nombre, rol, resultado, http_estado, motivo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, aparato_id, clave, accion, por, por_nombre, rol, resultado, http_estado, motivo, cuando
`

type AnotarRevisionDecisionParams struct {
	AparatoID  uuid.UUID `json:"aparato_id"`
	Clave      string    `json:"clave"`
	Accion     string    `json:"accion"`
	Por        string    `json:"por"`
	PorNombre  *string   `json:"por_nombre"`
	Rol        *string   `json:"rol"`
	Resultado  string    `json:"resultado"`
	HttpEstado *int32    `json:"http_estado"`
	Motivo     *string   `json:"motivo"`
}

// ===========================================================================
// 3 · El libro de decisiones (sólo se añade)
// ===========================================================================
func (q *Queries) AnotarRevisionDecision(ctx context.Context, arg AnotarRevisionDecisionParams) (RevisionDecisione, error) {
	row := q.db.QueryRow(ctx, anotarRevisionDecision,
		arg.AparatoID,
		arg.Clave,
		arg.Accion,
		arg.Por,
		arg.PorNombre,
		arg.Rol,
		arg.Resultado,
		arg.HttpEstado,
		arg.Motivo,
	)
	var i RevisionDecisione
	err := row.Scan(
		&i.ID,
		&i.AparatoID,
		&i.Clave,
		&i.Accion,
		&i.Por,
		&i.PorNombre,
		&i.Rol,
		&i.Resultado,
		&i.HttpEstado,
		&i.Motivo,
		&i.Cuando,
	)
	return i, err
}

const bloquearRevisionDeSucursal = `-- name: BloquearRevisionDeSucursal :exec
SELECT pg_advisory_xact_lock(hashtextextended('revision:' || $1::uuid::text, 0))
`

// Serializa las entregas de una sucursal para que contar el cupo y escribir sean UNA sola cosa: sin
// esto, N peticiones en paralelo pasarían todas por debajo del tope a la vez. Se suelta sola al acabar
// la transacción.
func (q *Queries) BloquearRevisionDeSucursal(ctx context.Context, sucursal uuid.UUID) error {
	_, err := q.db.Exec(ctx, bloquearRevisionDeSucursal, sucursal)
	return err
}

const cerrarRevisionComoAplicado = `-- name: CerrarRevisionComoAplicado :one
UPDATE revision_apuntes
SET estado = 'aplicado', motivo = NULL, intentos = intentos + 1,
    id_creado = $1::uuid, descartados = $2::jsonb
WHERE aparato_id = $3 AND clave = $4
  AND estado = 'aplicando' AND decidido_por = $5::text
RETURNING aparato_id, clave, entrega_id, orden, metodo, ruta, cuerpo, provisional, hecho_at, huella, resumen_del_aparato, estado, decidido_por, decidido_por_nombre, decidido_at, motivo, id_creado, descartados, intentos, created_at, updated_at
`

type CerrarRevisionComoAplicadoParams struct {
	IDCreado    pgtype.UUID `json:"id_creado"`
	Descartados []byte      `json:"descartados"`
	AparatoID   uuid.UUID   `json:"aparato_id"`
	Clave       string      `json:"clave"`
	Revisor     string      `json:"revisor"`
}

// El reparto dijo que sí. SÓLO cierra quien lo reclamó (`decidido_por`), y SÓLO desde `aplicando`.
func (q *Queries) CerrarRevisionComoAplicado(ctx context.Context, arg CerrarRevisionComoAplicadoParams) (RevisionApunte, error) {
	row := q.db.QueryRow(ctx, cerrarRevisionComoAplicado,
		arg.IDCreado,
		arg.Descartados,
		arg.AparatoID,
		arg.Clave,
		arg.Revisor,
	)
	var i RevisionApunte
	err := row.Scan(
		&i.AparatoID,
		&i.Clave,
		&i.EntregaID,
		&i.Orden,
		&i.Metodo,
		&i.Ruta,
		&i.Cuerpo,
		&i.Provisional,
		&i.HechoAt,
		&i.Huella,
		&i.ResumenDelAparato,
		&i.Estado,
		&i.DecididoPor,
		&i.DecididoPorNombre,
		&i.DecididoAt,
		&i.Motivo,
		&i.IDCreado,
		&i.Descartados,
		&i.Intentos,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cerrarRevisionComoRechazado = `-- name: CerrarRevisionComoRechazado :one
UPDATE revision_apuntes
SET estado = 'rechazado', motivo = $1::text, intentos = intentos + 1
WHERE aparato_id = $2 AND clave = $3
  AND estado = 'aplicando' AND decidido_por = $4::text
RETURNING aparato_id, clave, entrega_id, orden, metodo, ruta, cuerpo, provisional, hecho_at, huella, resumen_del_aparato, estado, decidido_por, decidido_por_nombre, decidido_at, motivo, id_creado, descartados, intentos, created_at, updated_at
`

type CerrarRevisionComoRechazadoParams struct {
	Motivo    string    `json:"motivo"`
	AparatoID uuid.UUID `json:"aparato_id"`
	Clave     string    `json:"clave"`
	Revisor   string    `json:"revisor"`
}

// El reparto dijo que no (un 4xx): se queda VIVO y a la vista, con el motivo LITERAL, esperando decisión.
// No se reintenta solo.
func (q *Queries) CerrarRevisionComoRechazado(ctx context.Context, arg CerrarRevisionComoRechazadoParams) (RevisionApunte, error) {
	row := q.db.QueryRow(ctx, cerrarRevisionComoRechazado,
		arg.Motivo,
		arg.AparatoID,
		arg.Clave,
		arg.Revisor,
	)
	var i RevisionApunte
	err := row.Scan(
		&i.AparatoID,
		&i.Clave,
		&i.EntregaID,
		&i.Orden,
		&i.Metodo,
		&i.Ruta,
		&i.Cuerpo,
		&i.Provisional,
		&i.HechoAt,
		&i.Huella,
		&i.ResumenDelAparato,
		&i.Estado,
		&i.DecididoPor,
		&i.DecididoPorNombre,
		&i.DecididoAt,
		&i.Motivo,
		&i.IDCreado,
		&i.Descartados,
		&i.Intentos,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const copiarApunteAplicadoAlLibro = `-- name: CopiarApunteAplicadoAlLibro :execrows
INSERT INTO apuntes (aparato_id, clave, metodo, ruta, estado, id_creado, hecho_at, descartados)
VALUES ($1, $2, $3, $4, 'aplicado', $5, $6, $7)
ON CONFLICT (aparato_id, clave) DO NOTHING
`

type CopiarApunteAplicadoAlLibroParams struct {
	AparatoID   uuid.UUID          `json:"aparato_id"`
	Clave       string             `json:"clave"`
	Metodo      string             `json:"metodo"`
	Ruta        string             `json:"ruta"`
	IDCreado    pgtype.UUID        `json:"id_creado"`
	HechoAt     pgtype.Timestamptz `json:"hecho_at"`
	Descartados []byte             `json:"descartados"`
}

// Al aplicar por revisión, el apunte se copia al libro `apuntes` (para que la reentrega normal dé `repetido`).
// SIN fallar si la clave YA estaba (auditoría final, B6): `aplicar` mira el libro antes de reenviar y no
// reenvía lo que ya está; esto es la red por si la subida normal de un sync viejo se coló entre mirar y
// escribir —la transacción no se cae por una fila que ya cuenta lo mismo—. Devuelve cuántas filas escribió.
func (q *Queries) CopiarApunteAplicadoAlLibro(ctx context.Context, arg CopiarApunteAplicadoAlLibroParams) (int64, error) {
	result, err := q.db.Exec(ctx, copiarApunteAplicadoAlLibro,
		arg.AparatoID,
		arg.Clave,
		arg.Metodo,
		arg.Ruta,
		arg.IDCreado,
		arg.HechoAt,
		arg.Descartados,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cupoDeRevision = `-- name: CupoDeRevision :one
SELECT (count(*) FILTER (WHERE e.persona = $1::text))::bigint AS de_la_persona,
       (COALESCE(sum(octet_length(a.cuerpo)) FILTER (WHERE e.persona = $1::text), 0))::bigint
           AS bytes_de_la_persona,
       (count(*) FILTER (WHERE e.branch_id = $2::uuid))::bigint AS de_la_sucursal
FROM revision_apuntes a
JOIN revision_entregas e ON e.id = a.entrega_id
WHERE a.estado IN ('en_revision', 'aplicando', 'rechazado')
  AND (e.persona = $1::text OR e.branch_id = $2::uuid)
`

type CupoDeRevisionParams struct {
	Persona  string    `json:"persona"`
	Sucursal uuid.UUID `json:"sucursal"`
}

type CupoDeRevisionRow struct {
	DeLaPersona      int64 `json:"de_la_persona"`
	BytesDeLaPersona int64 `json:"bytes_de_la_persona"`
	DeLaSucursal     int64 `json:"de_la_sucursal"`
}

// Los cupos de una persona y de una sucursal, sólo de lo VIVO. Una sola pasada.
func (q *Queries) CupoDeRevision(ctx context.Context, arg CupoDeRevisionParams) (CupoDeRevisionRow, error) {
	row := q.db.QueryRow(ctx, cupoDeRevision, arg.Persona, arg.Sucursal)
	var i CupoDeRevisionRow
	err := row.Scan(&i.DeLaPersona, &i.BytesDeLaPersona, &i.DeLaSucursal)
	return i, err
}

const descartarRevisionApunte = `-- name: DescartarRevisionApunte :one
UPDATE revision_apuntes AS a
SET estado = 'descartado',
    decidido_por = $1::text,
    decidido_por_nombre = $2::text,
    decidido_at = now(),
    motivo = $3::text
FROM revision_entregas e
WHERE e.id = a.entrega_id
  AND a.aparato_id = $4 AND a.clave = $5
  AND a.estado IN ('en_revision', 'rechazado')
  AND e.persona <> $1::text
  AND ($6::uuid IS NULL OR e.branch_id = $6::uuid)
RETURNING a.aparato_id, a.clave, a.entrega_id, a.orden, a.estado, a.decidido_por, a.decidido_por_nombre,
          a.decidido_at, a.motivo
`

type DescartarRevisionApunteParams struct {
	Revisor       string      `json:"revisor"`
	RevisorNombre *string     `json:"revisor_nombre"`
	Motivo        string      `json:"motivo"`
	AparatoID     uuid.UUID   `json:"aparato_id"`
	Clave         string      `json:"clave"`
	Sucursal      pgtype.UUID `json:"sucursal"`
}

type DescartarRevisionApunteRow struct {
	AparatoID         uuid.UUID          `json:"aparato_id"`
	Clave             string             `json:"clave"`
	EntregaID         uuid.UUID          `json:"entrega_id"`
	Orden             int32              `json:"orden"`
	Estado            RevisionEstado     `json:"estado"`
	DecididoPor       *string            `json:"decidido_por"`
	DecididoPorNombre *string            `json:"decidido_por_nombre"`
	DecididoAt        pgtype.Timestamptz `json:"decidido_at"`
	Motivo            *string            `json:"motivo"`
}

// DESCARTAR: SÓLO lo que sigue esperando, SÓLO de otra persona, SÓLO dentro del alcance, y con un motivo
// escrito (la base lo exige: ≥ 5 caracteres). No borra: marca `descartado` con quién y cuándo.
func (q *Queries) DescartarRevisionApunte(ctx context.Context, arg DescartarRevisionApunteParams) (DescartarRevisionApunteRow, error) {
	row := q.db.QueryRow(ctx, descartarRevisionApunte,
		arg.Revisor,
		arg.RevisorNombre,
		arg.Motivo,
		arg.AparatoID,
		arg.Clave,
		arg.Sucursal,
	)
	var i DescartarRevisionApunteRow
	err := row.Scan(
		&i.AparatoID,
		&i.Clave,
		&i.EntregaID,
		&i.Orden,
		&i.Estado,
		&i.DecididoPor,
		&i.DecididoPorNombre,
		&i.DecididoAt,
		&i.Motivo,
	)
	return i, err
}

const devolverRevisionAEnRevision = `-- name: DevolverRevisionAEnRevision :one
UPDATE revision_apuntes
SET estado = 'en_revision', intentos = intentos + 1,
    decidido_por = NULL, decidido_por_nombre = NULL, decidido_at = NULL
WHERE aparato_id = $1 AND clave = $2
  AND estado = 'aplicando' AND decidido_por = $3::text
RETURNING aparato_id, clave, entrega_id, orden, metodo, ruta, cuerpo, provisional, hecho_at, huella, resumen_del_aparato, estado, decidido_por, decidido_por_nombre, decidido_at, motivo, id_creado, descartados, intentos, created_at, updated_at
`

type DevolverRevisionAEnRevisionParams struct {
	AparatoID uuid.UUID `json:"aparato_id"`
	Clave     string    `json:"clave"`
	Revisor   string    `json:"revisor"`
}

// Una caída (5xx o red), no un rechazo: vuelve a `en_revision` con un intento más, sin dueño.
func (q *Queries) DevolverRevisionAEnRevision(ctx context.Context, arg DevolverRevisionAEnRevisionParams) (RevisionApunte, error) {
	row := q.db.QueryRow(ctx, devolverRevisionAEnRevision, arg.AparatoID, arg.Clave, arg.Revisor)
	var i RevisionApunte
	err := row.Scan(
		&i.AparatoID,
		&i.Clave,
		&i.EntregaID,
		&i.Orden,
		&i.Metodo,
		&i.Ruta,
		&i.Cuerpo,
		&i.Provisional,
		&i.HechoAt,
		&i.Huella,
		&i.ResumenDelAparato,
		&i.Estado,
		&i.DecididoPor,
		&i.DecididoPorNombre,
		&i.DecididoAt,
		&i.Motivo,
		&i.IDCreado,
		&i.Descartados,
		&i.Intentos,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const estadoDeRevisionDeApunte = `-- name: EstadoDeRevisionDeApunte :one
SELECT aparato_id, clave, entrega_id, orden, estado, huella, motivo, id_creado, descartados,
       decidido_por_nombre, decidido_at
FROM revision_apuntes
WHERE aparato_id = $1 AND clave = $2
`

type EstadoDeRevisionDeApunteParams struct {
	AparatoID uuid.UUID `json:"aparato_id"`
	Clave     string    `json:"clave"`
}

type EstadoDeRevisionDeApunteRow struct {
	AparatoID         uuid.UUID          `json:"aparato_id"`
	Clave             string             `json:"clave"`
	EntregaID         uuid.UUID          `json:"entrega_id"`
	Orden             int32              `json:"orden"`
	Estado            RevisionEstado     `json:"estado"`
	Huella            string             `json:"huella"`
	Motivo            *string            `json:"motivo"`
	IDCreado          pgtype.UUID        `json:"id_creado"`
	Descartados       []byte             `json:"descartados"`
	DecididoPorNombre *string            `json:"decidido_por_nombre"`
	DecididoAt        pgtype.Timestamptz `json:"decidido_at"`
}

// «¿He visto ya esta clave?», SIN el cuerpo (que puede pesar 128 KiB): se pregunta una vez por cada
// apunte de CADA subida normal y de cada entrega. Va por la primaria.
func (q *Queries) EstadoDeRevisionDeApunte(ctx context.Context, arg EstadoDeRevisionDeApunteParams) (EstadoDeRevisionDeApunteRow, error) {
	row := q.db.QueryRow(ctx, estadoDeRevisionDeApunte, arg.AparatoID, arg.Clave)
	var i EstadoDeRevisionDeApunteRow
	err := row.Scan(
		&i.AparatoID,
		&i.Clave,
		&i.EntregaID,
		&i.Orden,
		&i.Estado,
		&i.Huella,
		&i.Motivo,
		&i.IDCreado,
		&i.Descartados,
		&i.DecididoPorNombre,
		&i.DecididoAt,
	)
	return i, err
}

const insertarRevisionApunte = `-- name: InsertarRevisionApunte :one
INSERT INTO revision_apuntes (aparato_id, clave, entrega_id, orden, metodo, ruta, cuerpo, provisional,
                              hecho_at, huella, resumen_del_aparato)
VALUES ($1, $2, $3,
        (SELECT COALESCE(MAX(orden), -1) + 1 FROM revision_apuntes WHERE aparato_id = $1),
        $4, $5, $6, $7,
        $8, $9, $10)
ON CONFLICT (aparato_id, clave) DO NOTHING
RETURNING aparato_id, clave, entrega_id, orden, metodo, ruta, cuerpo, provisional, hecho_at, huella, resumen_del_aparato, estado, decidido_por, decidido_por_nombre, decidido_at, motivo, id_creado, descartados, intentos, created_at, updated_at
`

type InsertarRevisionApunteParams struct {
	AparatoID         uuid.UUID          `json:"aparato_id"`
	Clave             string             `json:"clave"`
	EntregaID         uuid.UUID          `json:"entrega_id"`
	Metodo            string             `json:"metodo"`
	Ruta              string             `json:"ruta"`
	Cuerpo            *string            `json:"cuerpo"`
	Provisional       *string            `json:"provisional"`
	HechoAt           pgtype.Timestamptz `json:"hecho_at"`
	Huella            string             `json:"huella"`
	ResumenDelAparato *string            `json:"resumen_del_aparato"`
}

// La idempotencia: reentregar la misma clave NO inserta (y no devuelve fila). Quien llama ya miró
// `EstadoDeRevisionDeApunte`; esto es la red contra dos peticiones a la vez. El orden FIFO lo pone el
// servidor, por orden de llegada dentro del aparato.
func (q *Queries) InsertarRevisionApunte(ctx context.Context, arg InsertarRevisionApunteParams) (RevisionApunte, error) {
	row := q.db.QueryRow(ctx, insertarRevisionApunte,
		arg.AparatoID,
		arg.Clave,
		arg.EntregaID,
		arg.Metodo,
		arg.Ruta,
		arg.Cuerpo,
		arg.Provisional,
		arg.HechoAt,
		arg.Huella,
		arg.ResumenDelAparato,
	)
	var i RevisionApunte
	err := row.Scan(
		&i.AparatoID,
		&i.Clave,
		&i.EntregaID,
		&i.Orden,
		&i.Metodo,
		&i.Ruta,
		&i.Cuerpo,
		&i.Provisional,
		&i.HechoAt,
		&i.Huella,
		&i.ResumenDelAparato,
		&i.Estado,
		&i.DecididoPor,
		&i.DecididoPorNombre,
		&i.DecididoAt,
		&i.Motivo,
		&i.IDCreado,
		&i.Descartados,
		&i.Intentos,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listarEntregasParaRevisor = `-- name: ListarEntregasParaRevisor :many
SELECT e.id, e.aparato_id, COALESCE(left(p.nombre, 200), '')::text AS aparato_nombre, e.persona, e.persona_nombre, e.branch_id,
       e.entregada_at, e.version_app,
       (count(*) FILTER (WHERE a.estado = 'en_revision'))::bigint AS en_revision,
       (count(*) FILTER (WHERE a.estado = 'aplicando'))::bigint   AS aplicando,
       (count(*) FILTER (WHERE a.estado = 'rechazado'))::bigint   AS rechazados,
       (count(*) FILTER (WHERE a.estado = 'aplicado'))::bigint    AS aplicados,
       (count(*) FILTER (WHERE a.estado = 'descartado'))::bigint  AS descartados
FROM revision_entregas e
JOIN revision_apuntes a ON a.entrega_id = e.id
JOIN aparatos p ON p.id = e.aparato_id
WHERE ($1::uuid IS NULL OR e.branch_id = $1::uuid)
GROUP BY e.id, p.id
HAVING count(*) FILTER (WHERE a.estado IN ('en_revision', 'aplicando', 'rechazado')) > 0
ORDER BY e.entregada_at, e.id
LIMIT $2::int
`

type ListarEntregasParaRevisorParams struct {
	Sucursal pgtype.UUID `json:"sucursal"`
	Limite   int32       `json:"limite"`
}

type ListarEntregasParaRevisorRow struct {
	ID            uuid.UUID          `json:"id"`
	AparatoID     uuid.UUID          `json:"aparato_id"`
	AparatoNombre string             `json:"aparato_nombre"`
	Persona       string             `json:"persona"`
	PersonaNombre *string            `json:"persona_nombre"`
	BranchID      uuid.UUID          `json:"branch_id"`
	EntregadaAt   pgtype.Timestamptz `json:"entregada_at"`
	VersionApp    *string            `json:"version_app"`
	EnRevision    int64              `json:"en_revision"`
	Aplicando     int64              `json:"aplicando"`
	Rechazados    int64              `json:"rechazados"`
	Aplicados     int64              `json:"aplicados"`
	Descartados   int64              `json:"descartados"`
}

// La bandeja del revisor, UNA FILA POR ENTREGA con sus cuentas por estado (exactas: se cuenta TODO lo de la
// entrega, no sólo lo vivo) y sólo las que aún tienen algo esperando. Con el alcance dentro; el tope lo
// comprueba quien llama (pide uno más de lo que va a enseñar).
func (q *Queries) ListarEntregasParaRevisor(ctx context.Context, arg ListarEntregasParaRevisorParams) ([]ListarEntregasParaRevisorRow, error) {
	rows, err := q.db.Query(ctx, listarEntregasParaRevisor, arg.Sucursal, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarEntregasParaRevisorRow
	for rows.Next() {
		var i ListarEntregasParaRevisorRow
		if err := rows.Scan(
			&i.ID,
			&i.AparatoID,
			&i.AparatoNombre,
			&i.Persona,
			&i.PersonaNombre,
			&i.BranchID,
			&i.EntregadaAt,
			&i.VersionApp,
			&i.EnRevision,
			&i.Aplicando,
			&i.Rechazados,
			&i.Aplicados,
			&i.Descartados,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarRevisionParaRevisor = `-- name: ListarRevisionParaRevisor :many

SELECT a.aparato_id, a.clave, a.entrega_id, a.orden, a.estado, a.metodo, a.ruta, a.hecho_at,
       a.resumen_del_aparato, a.decidido_por, a.decidido_por_nombre, a.decidido_at, a.motivo, a.id_creado,
       a.intentos, a.updated_at,
       e.persona, e.persona_nombre, e.branch_id, e.entregada_at, COALESCE(left(p.nombre, 200), '')::text AS aparato_nombre
FROM revision_apuntes a
JOIN revision_entregas e ON e.id = a.entrega_id
JOIN aparatos p ON p.id = a.aparato_id
WHERE ($1::uuid IS NULL OR e.branch_id = $1::uuid)
  AND (NOT $2::boolean OR a.estado IN ('en_revision', 'aplicando', 'rechazado'))
  AND ($3::revision_estado IS NULL OR a.estado = $3::revision_estado)
ORDER BY e.entregada_at, a.orden, a.clave
LIMIT $4::int
`

type ListarRevisionParaRevisorParams struct {
	Sucursal  pgtype.UUID     `json:"sucursal"`
	SoloVivos bool            `json:"solo_vivos"`
	Estado    *RevisionEstado `json:"estado"`
	Limite    int32           `json:"limite"`
}

type ListarRevisionParaRevisorRow struct {
	AparatoID         uuid.UUID          `json:"aparato_id"`
	Clave             string             `json:"clave"`
	EntregaID         uuid.UUID          `json:"entrega_id"`
	Orden             int32              `json:"orden"`
	Estado            RevisionEstado     `json:"estado"`
	Metodo            string             `json:"metodo"`
	Ruta              string             `json:"ruta"`
	HechoAt           pgtype.Timestamptz `json:"hecho_at"`
	ResumenDelAparato *string            `json:"resumen_del_aparato"`
	DecididoPor       *string            `json:"decidido_por"`
	DecididoPorNombre *string            `json:"decidido_por_nombre"`
	DecididoAt        pgtype.Timestamptz `json:"decidido_at"`
	Motivo            *string            `json:"motivo"`
	IDCreado          pgtype.UUID        `json:"id_creado"`
	Intentos          int32              `json:"intentos"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Persona           string             `json:"persona"`
	PersonaNombre     *string            `json:"persona_nombre"`
	BranchID          uuid.UUID          `json:"branch_id"`
	EntregadaAt       pgtype.Timestamptz `json:"entregada_at"`
	AparatoNombre     string             `json:"aparato_nombre"`
}

// ===========================================================================
// 2 · El revisor (S2)
// ===========================================================================
// La lista: lo de las sucursales que este revisor ve, lo más antiguo primero (FIFO), sin el cuerpo.
// `solo_vivos` deja fuera lo decidido; `estado` (opcional) estrecha a uno.
func (q *Queries) ListarRevisionParaRevisor(ctx context.Context, arg ListarRevisionParaRevisorParams) ([]ListarRevisionParaRevisorRow, error) {
	rows, err := q.db.Query(ctx, listarRevisionParaRevisor,
		arg.Sucursal,
		arg.SoloVivos,
		arg.Estado,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarRevisionParaRevisorRow
	for rows.Next() {
		var i ListarRevisionParaRevisorRow
		if err := rows.Scan(
			&i.AparatoID,
			&i.Clave,
			&i.EntregaID,
			&i.Orden,
			&i.Estado,
			&i.Metodo,
			&i.Ruta,
			&i.HechoAt,
			&i.ResumenDelAparato,
			&i.DecididoPor,
			&i.DecididoPorNombre,
			&i.DecididoAt,
			&i.Motivo,
			&i.IDCreado,
			&i.Intentos,
			&i.UpdatedAt,
			&i.Persona,
			&i.PersonaNombre,
			&i.BranchID,
			&i.EntregadaAt,
			&i.AparatoNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reclamarRevisionApunte = `-- name: ReclamarRevisionApunte :one
UPDATE revision_apuntes AS a
SET estado = 'aplicando',
    decidido_por = $1::text,
    decidido_por_nombre = $2::text,
    decidido_at = now()
FROM revision_entregas e
WHERE e.id = a.entrega_id
  AND a.aparato_id = $3 AND a.clave = $4
  AND a.estado IN ('en_revision', 'rechazado')
  AND e.persona <> $1::text
  AND ($5::uuid IS NULL OR e.branch_id = $5::uuid)
RETURNING a.aparato_id, a.clave, a.entrega_id, a.orden, a.estado, a.metodo, a.ruta, a.cuerpo, a.provisional,
          a.hecho_at, a.huella, a.decidido_por, a.decidido_por_nombre, a.decidido_at, a.intentos
`

type ReclamarRevisionApunteParams struct {
	Revisor       string      `json:"revisor"`
	RevisorNombre *string     `json:"revisor_nombre"`
	AparatoID     uuid.UUID   `json:"aparato_id"`
	Clave         string      `json:"clave"`
	Sucursal      pgtype.UUID `json:"sucursal"`
}

type ReclamarRevisionApunteRow struct {
	AparatoID         uuid.UUID          `json:"aparato_id"`
	Clave             string             `json:"clave"`
	EntregaID         uuid.UUID          `json:"entrega_id"`
	Orden             int32              `json:"orden"`
	Estado            RevisionEstado     `json:"estado"`
	Metodo            string             `json:"metodo"`
	Ruta              string             `json:"ruta"`
	Cuerpo            *string            `json:"cuerpo"`
	Provisional       *string            `json:"provisional"`
	HechoAt           pgtype.Timestamptz `json:"hecho_at"`
	Huella            string             `json:"huella"`
	DecididoPor       *string            `json:"decidido_por"`
	DecididoPorNombre *string            `json:"decidido_por_nombre"`
	DecididoAt        pgtype.Timestamptz `json:"decidido_at"`
	Intentos          int32              `json:"intentos"`
}

// EL CANDADO. Pasa a `aplicando` SÓLO lo que sigue esperando (`en_revision`, o `rechazado` para
// reintentar), SÓLO si lo entregó otra persona (nadie revisa lo suyo) y SÓLO dentro del alcance del
// revisor. Devuelve la fila o ninguna: dos revisores a la vez, un solo ganador.
func (q *Queries) ReclamarRevisionApunte(ctx context.Context, arg ReclamarRevisionApunteParams) (ReclamarRevisionApunteRow, error) {
	row := q.db.QueryRow(ctx, reclamarRevisionApunte,
		arg.Revisor,
		arg.RevisorNombre,
		arg.AparatoID,
		arg.Clave,
		arg.Sucursal,
	)
	var i ReclamarRevisionApunteRow
	err := row.Scan(
		&i.AparatoID,
		&i.Clave,
		&i.EntregaID,
		&i.Orden,
		&i.Estado,
		&i.Metodo,
		&i.Ruta,
		&i.Cuerpo,
		&i.Provisional,
		&i.HechoAt,
		&i.Huella,
		&i.DecididoPor,
		&i.DecididoPorNombre,
		&i.DecididoAt,
		&i.Intentos,
	)
	return i, err
}

const reclamarRevisionInterrumpida = `-- name: ReclamarRevisionInterrumpida :one
UPDATE revision_apuntes AS a
SET decidido_por = $1::text,
    decidido_por_nombre = $2::text,
    decidido_at = now()
FROM revision_entregas e
WHERE e.id = a.entrega_id
  AND a.aparato_id = $3 AND a.clave = $4
  AND a.estado = 'aplicando'
  AND a.updated_at < now() - make_interval(secs => $5::int)
  AND e.persona <> $1::text
  AND ($6::uuid IS NULL OR e.branch_id = $6::uuid)
RETURNING a.aparato_id, a.clave, a.entrega_id, a.orden, a.estado, a.metodo, a.ruta, a.cuerpo, a.provisional,
          a.hecho_at, a.huella, a.decidido_por, a.decidido_por_nombre, a.decidido_at, a.intentos
`

type ReclamarRevisionInterrumpidaParams struct {
	Revisor            string      `json:"revisor"`
	RevisorNombre      *string     `json:"revisor_nombre"`
	AparatoID          uuid.UUID   `json:"aparato_id"`
	Clave              string      `json:"clave"`
	AntiguedadSegundos int32       `json:"antiguedad_segundos"`
	Sucursal           pgtype.UUID `json:"sucursal"`
}

type ReclamarRevisionInterrumpidaRow struct {
	AparatoID         uuid.UUID          `json:"aparato_id"`
	Clave             string             `json:"clave"`
	EntregaID         uuid.UUID          `json:"entrega_id"`
	Orden             int32              `json:"orden"`
	Estado            RevisionEstado     `json:"estado"`
	Metodo            string             `json:"metodo"`
	Ruta              string             `json:"ruta"`
	Cuerpo            *string            `json:"cuerpo"`
	Provisional       *string            `json:"provisional"`
	HechoAt           pgtype.Timestamptz `json:"hecho_at"`
	Huella            string             `json:"huella"`
	DecididoPor       *string            `json:"decidido_por"`
	DecididoPorNombre *string            `json:"decidido_por_nombre"`
	DecididoAt        pgtype.Timestamptz `json:"decidido_at"`
	Intentos          int32              `json:"intentos"`
}

// Un apunte que se quedó en `aplicando` porque el proceso murió: SÓLO pasa a manos de un revisor si lleva
// más de `antiguedad_segundos` así, y quien llama ya confirmó a mano que la ruta no se aplicó (la API no
// lee `X-Apunte`: no hay otra red). Mismas condiciones de alcance y de autor que `ReclamarRevisionApunte`.
func (q *Queries) ReclamarRevisionInterrumpida(ctx context.Context, arg ReclamarRevisionInterrumpidaParams) (ReclamarRevisionInterrumpidaRow, error) {
	row := q.db.QueryRow(ctx, reclamarRevisionInterrumpida,
		arg.Revisor,
		arg.RevisorNombre,
		arg.AparatoID,
		arg.Clave,
		arg.AntiguedadSegundos,
		arg.Sucursal,
	)
	var i ReclamarRevisionInterrumpidaRow
	err := row.Scan(
		&i.AparatoID,
		&i.Clave,
		&i.EntregaID,
		&i.Orden,
		&i.Estado,
		&i.Metodo,
		&i.Ruta,
		&i.Cuerpo,
		&i.Provisional,
		&i.HechoAt,
		&i.Huella,
		&i.DecididoPor,
		&i.DecididoPorNombre,
		&i.DecididoAt,
		&i.Intentos,
	)
	return i, err
}

const revisionApunteDeRevisor = `-- name: RevisionApunteDeRevisor :one
SELECT a.aparato_id, a.clave, a.entrega_id, a.orden, a.estado, a.metodo, a.ruta, a.cuerpo, a.provisional,
       a.hecho_at, a.huella, a.resumen_del_aparato, a.decidido_por, a.decidido_por_nombre, a.decidido_at,
       a.motivo, a.id_creado, a.descartados, a.intentos, a.created_at, a.updated_at,
       e.persona, e.persona_nombre, e.branch_id, e.entregada_at, e.token_jti, e.desde_ip, e.agente,
       e.version_app, COALESCE(left(p.nombre, 200), '')::text AS aparato_nombre
FROM revision_apuntes a
JOIN revision_entregas e ON e.id = a.entrega_id
JOIN aparatos p ON p.id = a.aparato_id
WHERE a.aparato_id = $1 AND a.clave = $2
  AND ($3::uuid IS NULL OR e.branch_id = $3::uuid)
`

type RevisionApunteDeRevisorParams struct {
	AparatoID uuid.UUID   `json:"aparato_id"`
	Clave     string      `json:"clave"`
	Sucursal  pgtype.UUID `json:"sucursal"`
}

type RevisionApunteDeRevisorRow struct {
	AparatoID         uuid.UUID          `json:"aparato_id"`
	Clave             string             `json:"clave"`
	EntregaID         uuid.UUID          `json:"entrega_id"`
	Orden             int32              `json:"orden"`
	Estado            RevisionEstado     `json:"estado"`
	Metodo            string             `json:"metodo"`
	Ruta              string             `json:"ruta"`
	Cuerpo            *string            `json:"cuerpo"`
	Provisional       *string            `json:"provisional"`
	HechoAt           pgtype.Timestamptz `json:"hecho_at"`
	Huella            string             `json:"huella"`
	ResumenDelAparato *string            `json:"resumen_del_aparato"`
	DecididoPor       *string            `json:"decidido_por"`
	DecididoPorNombre *string            `json:"decidido_por_nombre"`
	DecididoAt        pgtype.Timestamptz `json:"decidido_at"`
	Motivo            *string            `json:"motivo"`
	IDCreado          pgtype.UUID        `json:"id_creado"`
	Descartados       []byte             `json:"descartados"`
	Intentos          int32              `json:"intentos"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Persona           string             `json:"persona"`
	PersonaNombre     *string            `json:"persona_nombre"`
	BranchID          uuid.UUID          `json:"branch_id"`
	EntregadaAt       pgtype.Timestamptz `json:"entregada_at"`
	TokenJti          string             `json:"token_jti"`
	DesdeIp           *string            `json:"desde_ip"`
	Agente            *string            `json:"agente"`
	VersionApp        *string            `json:"version_app"`
	AparatoNombre     string             `json:"aparato_nombre"`
}

// Un apunte entero (con el cuerpo, que es lo que el revisor tiene que ver antes de pulsar), CON EL
// ALCANCE DENTRO: el administrador de CAM no lee ni aplica lo de HOL, ni por lista ni por id.
func (q *Queries) RevisionApunteDeRevisor(ctx context.Context, arg RevisionApunteDeRevisorParams) (RevisionApunteDeRevisorRow, error) {
	row := q.db.QueryRow(ctx, revisionApunteDeRevisor, arg.AparatoID, arg.Clave, arg.Sucursal)
	var i RevisionApunteDeRevisorRow
	err := row.Scan(
		&i.AparatoID,
		&i.Clave,
		&i.EntregaID,
		&i.Orden,
		&i.Estado,
		&i.Metodo,
		&i.Ruta,
		&i.Cuerpo,
		&i.Provisional,
		&i.HechoAt,
		&i.Huella,
		&i.ResumenDelAparato,
		&i.DecididoPor,
		&i.DecididoPorNombre,
		&i.DecididoAt,
		&i.Motivo,
		&i.IDCreado,
		&i.Descartados,
		&i.Intentos,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Persona,
		&i.PersonaNombre,
		&i.BranchID,
		&i.EntregadaAt,
		&i.TokenJti,
		&i.DesdeIp,
		&i.Agente,
		&i.VersionApp,
		&i.AparatoNombre,
	)
	return i, err
}

const revisionDeAparato = `-- name: RevisionDeAparato :many
SELECT clave, entrega_id, orden, estado, decidido_por_nombre, decidido_at, motivo, id_creado, descartados,
       updated_at
FROM revision_apuntes
WHERE aparato_id = $1
ORDER BY (estado IN ('en_revision', 'aplicando', 'rechazado')) DESC, updated_at DESC, clave
LIMIT $2::int
`

type RevisionDeAparatoParams struct {
	AparatoID uuid.UUID `json:"aparato_id"`
	Limite    int32     `json:"limite"`
}

type RevisionDeAparatoRow struct {
	Clave             string             `json:"clave"`
	EntregaID         uuid.UUID          `json:"entrega_id"`
	Orden             int32              `json:"orden"`
	Estado            RevisionEstado     `json:"estado"`
	DecididoPorNombre *string            `json:"decidido_por_nombre"`
	DecididoAt        pgtype.Timestamptz `json:"decidido_at"`
	Motivo            *string            `json:"motivo"`
	IDCreado          pgtype.UUID        `json:"id_creado"`
	Descartados       []byte             `json:"descartados"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// `GET /sync/revision/mias`: qué ha pasado con lo de este aparato. Lo vivo primero y, dentro, lo más
// reciente. Sin el cuerpo. El tope lo comprueba quien llama (pide uno más de lo que va a enseñar).
func (q *Queries) RevisionDeAparato(ctx context.Context, arg RevisionDeAparatoParams) ([]RevisionDeAparatoRow, error) {
	rows, err := q.db.Query(ctx, revisionDeAparato, arg.AparatoID, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevisionDeAparatoRow
	for rows.Next() {
		var i RevisionDeAparatoRow
		if err := rows.Scan(
			&i.Clave,
			&i.EntregaID,
			&i.Orden,
			&i.Estado,
			&i.DecididoPorNombre,
			&i.DecididoAt,
			&i.Motivo,
			&i.IDCreado,
			&i.Descartados,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revisionDeEntrega = `-- name: RevisionDeEntrega :many
SELECT a.aparato_id, a.clave, a.entrega_id, a.orden, a.estado, a.metodo, a.ruta, a.cuerpo, a.provisional,
       a.hecho_at, a.huella, a.resumen_del_aparato, a.decidido_por, a.decidido_por_nombre, a.decidido_at,
       a.motivo, a.id_creado, a.descartados, a.intentos,
       e.persona, e.persona_nombre, e.branch_id, e.entregada_at
FROM revision_apuntes a
JOIN revision_entregas e ON e.id = a.entrega_id
WHERE a.entrega_id = $1
  AND ($2::uuid IS NULL OR e.branch_id = $2::uuid)
ORDER BY a.orden, a.clave
`

type RevisionDeEntregaParams struct {
	EntregaID uuid.UUID   `json:"entrega_id"`
	Sucursal  pgtype.UUID `json:"sucursal"`
}

type RevisionDeEntregaRow struct {
	AparatoID         uuid.UUID          `json:"aparato_id"`
	Clave             string             `json:"clave"`
	EntregaID         uuid.UUID          `json:"entrega_id"`
	Orden             int32              `json:"orden"`
	Estado            RevisionEstado     `json:"estado"`
	Metodo            string             `json:"metodo"`
	Ruta              string             `json:"ruta"`
	Cuerpo            *string            `json:"cuerpo"`
	Provisional       *string            `json:"provisional"`
	HechoAt           pgtype.Timestamptz `json:"hecho_at"`
	Huella            string             `json:"huella"`
	ResumenDelAparato *string            `json:"resumen_del_aparato"`
	DecididoPor       *string            `json:"decidido_por"`
	DecididoPorNombre *string            `json:"decidido_por_nombre"`
	DecididoAt        pgtype.Timestamptz `json:"decidido_at"`
	Motivo            *string            `json:"motivo"`
	IDCreado          pgtype.UUID        `json:"id_creado"`
	Descartados       []byte             `json:"descartados"`
	Intentos          int32              `json:"intentos"`
	Persona           string             `json:"persona"`
	PersonaNombre     *string            `json:"persona_nombre"`
	BranchID          uuid.UUID          `json:"branch_id"`
	EntregadaAt       pgtype.Timestamptz `json:"entregada_at"`
}

// Una entrega entera, en orden, con el alcance dentro. Es lo que recorre «Aplicar todo en orden».
func (q *Queries) RevisionDeEntrega(ctx context.Context, arg RevisionDeEntregaParams) ([]RevisionDeEntregaRow, error) {
	rows, err := q.db.Query(ctx, revisionDeEntrega, arg.EntregaID, arg.Sucursal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevisionDeEntregaRow
	for rows.Next() {
		var i RevisionDeEntregaRow
		if err := rows.Scan(
			&i.AparatoID,
			&i.Clave,
			&i.EntregaID,
			&i.Orden,
			&i.Estado,
			&i.Metodo,
			&i.Ruta,
			&i.Cuerpo,
			&i.Provisional,
			&i.HechoAt,
			&i.Huella,
			&i.ResumenDelAparato,
			&i.DecididoPor,
			&i.DecididoPorNombre,
			&i.DecididoAt,
			&i.Motivo,
			&i.IDCreado,
			&i.Descartados,
			&i.Intentos,
			&i.Persona,
			&i.PersonaNombre,
			&i.BranchID,
			&i.EntregadaAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revisionDecisionesDeApunte = `-- name: RevisionDecisionesDeApunte :many
SELECT id, aparato_id, clave, accion, por, por_nombre, rol, resultado, http_estado, motivo, cuando FROM revision_decisiones
WHERE aparato_id = $1 AND clave = $2
ORDER BY cuando, id
`

type RevisionDecisionesDeApunteParams struct {
	AparatoID uuid.UUID `json:"aparato_id"`
	Clave     string    `json:"clave"`
}

func (q *Queries) RevisionDecisionesDeApunte(ctx context.Context, arg RevisionDecisionesDeApunteParams) ([]RevisionDecisione, error) {
	rows, err := q.db.Query(ctx, revisionDecisionesDeApunte, arg.AparatoID, arg.Clave)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevisionDecisione
	for rows.Next() {
		var i RevisionDecisione
		if err := rows.Scan(
			&i.ID,
			&i.AparatoID,
			&i.Clave,
			&i.Accion,
			&i.Por,
			&i.PorNombre,
			&i.Rol,
			&i.Resultado,
			&i.HttpEstado,
			&i.Motivo,
			&i.Cuando,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revisionEntregaPorId = `-- name: RevisionEntregaPorId :one
SELECT id, persona, branch_id FROM revision_entregas WHERE id = $1
`

type RevisionEntregaPorIdRow struct {
	ID       uuid.UUID `json:"id"`
	Persona  string    `json:"persona"`
	BranchID uuid.UUID `json:"branch_id"`
}

// SIN alcance, a propósito, y SIN cuerpo: sólo para decidir CÓMO se dice «no» cuando la consulta con
// alcance no encontró nada (404 si no existe; 403 si existe en una sucursal que el revisor no ve). Nunca
// decide un permiso: la decisión es la consulta con alcance, esta sólo pone la frase.
func (q *Queries) RevisionEntregaPorId(ctx context.Context, id uuid.UUID) (RevisionEntregaPorIdRow, error) {
	row := q.db.QueryRow(ctx, revisionEntregaPorId, id)
	var i RevisionEntregaPorIdRow
	err := row.Scan(&i.ID, &i.Persona, &i.BranchID)
	return i, err
}

const revisionSinDecidirPorSucursal = `-- name: RevisionSinDecidirPorSucursal :many
SELECT e.branch_id, count(*) AS en_revision
FROM revision_apuntes a
JOIN revision_entregas e ON e.id = a.entrega_id
WHERE a.estado IN ('en_revision', 'aplicando', 'rechazado')
  AND ($1::uuid IS NULL OR e.branch_id = $1::uuid)
GROUP BY e.branch_id
ORDER BY en_revision DESC
`

type RevisionSinDecidirPorSucursalRow struct {
	BranchID   uuid.UUID `json:"branch_id"`
	EnRevision int64     `json:"en_revision"`
}

// El segundo «número rojo» de `/sync/estado`, por sucursal.
func (q *Queries) RevisionSinDecidirPorSucursal(ctx context.Context, sucursal pgtype.UUID) ([]RevisionSinDecidirPorSucursalRow, error) {
	rows, err := q.db.Query(ctx, revisionSinDecidirPorSucursal, sucursal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevisionSinDecidirPorSucursalRow
	for rows.Next() {
		var i RevisionSinDecidirPorSucursalRow
		if err := rows.Scan(&i.BranchID, &i.EnRevision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
